import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { Toaster } from "@/components/ui/sonner";
import { env } from "@/env";
import { AuthProvider } from "@/components/AuthProvider";
import { getServerAuth } from "@/lib/auth";

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: env.NEXT_PUBLIC_APP_NAME,
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await getServerAuth();
  console.log(data);
  return (
    <html lang="en">
      <body className={`${inter.className} ${inter.variable} antialiased`}>
        <AuthProvider initialUser={data?.data || null}>{children}</AuthProvider>
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
