export const tableData = [
  {
    "id": 1,
    "first_name": "John",
    "last_name": "Doe",
    "email": "john.doe@example.com",
    "gender": "Male",
    "ip_address": "192.168.1.1",
  },
  {
    "id": 2,
    "first_name": "Jane",
    "last_name": "Doe",
    "email": "jane.doe@example.com",
    "gender": "Female",
    "ip_address": "192.168.1.2",
  },
  {
    "id": 3,
    "first_name": "Peter",
    "last_name": "Jones",
    "email": "peter.jones@example.com",
    "gender": "Male",
    "ip_address": "192.168.1.3",
  },
  {
    "id": 4,
    "first_name": "Mary",
    "last_name": "Smith",
    "email": "mary.smith@example.com",
    "gender": "Female",
    "ip_address": "192.168.1.4",
  },
  {
    "id": 5,
    "first_name": "David",
    "last_name": "Williams",
    "email": "david.williams@example.com",
    "gender": "Male",
    "ip_address": "192.168.1.5",
  },
  {
    "id": 6,
    "first_name": "Susan",
    "last_name": "Brown",
    "email": "susan.brown@example.com",
    "gender": "Female",
    "ip_address": "192.168.1.6",
  },
  {
    "id": 7,
    "first_name": "Richard",
    "last_name": "Davis",
    "email": "richard.davis@example.com",
    "gender": "Male",
    "ip_address": "192.168.1.7",
  },
  {
    "id": 8,
    "first_name": "Karen",
    "last_name": "Miller",
    "email": "karen.miller@example.com",
    "gender": "Female",
    "ip_address": "192.168.1.8",
  },
  {
    "id": 9,
    "first_name": "Charles",
    "last_name": "Wilson",
    "email": "charles.wilson@example.com",
    "gender": "Male",
    "ip_address": "192.168.1.9",
  },
  {
    "id": 10,
    "first_name": "Jessica",
    "last_name": "Moore",
    "email": "jessica.moore@example.com",
    "gender": "Female",
    "ip_address": "192.168.1.10",
  },
];